### ISSUE TITLE
Git pull request 관련 문의

### ISSUE THREAD

**Issue by keetae423** [swsnu/swppfall2022#129]
현재 github pull request가 되지 않아 문의 드립니다. 

![2022-10-13 03_47_17-](https://user-images.githubusercontent.com/55076957/195424859-5d8e0543-7ad3-405d-8f1c-fbf6225ec7a2.png)
![2022-10-13 03_47_28-Fork swpp22fall-practice-sessions_swpp-p6-django-tutorial - Chrome](https://user-images.githubusercontent.com/55076957/195425054-d0484112-b52e-43f0-b78b-853b5b86aa80.png)
평소처럼 Fork 진행한 후 Repository를 만들었습니다.

이후 실습을 마무리하고 다음과 같이 명령어를 입력하였습니다.
git init
git add .
git commit -m "lab06"
git branch -M main
git remote add origin https://github.com/keetae423/swpp-p6-django-tutorial
git push -u origin main
![2022-10-13 03_51_30-keetae423_swpp-p6-django-tutorial - Chrome](https://user-images.githubusercontent.com/55076957/195425390-d31329a5-912a-4927-bcf4-89f4bf22c83c.png)
![2022-10-13 03_51_46-keetae423_swpp-p6-django-tutorial - Chrome](https://user-images.githubusercontent.com/55076957/195425421-65f6b7c3-5639-4f41-bfd6-973ae5937a01.png)

그런데 아래 사진처럼 create and pull request 버튼이 없어서 지금 제출을 못하고 있습니다. 되게 간단한 실수일 것 같은데 해결책 아시는 분 말씀해주시면 감사하겠습니다.
![2022-10-13 03_52_54-keetae423_swpp-p6-django-tutorial at main - Chrome](https://user-images.githubusercontent.com/55076957/195425574-4ec3f232-6fc2-49e3-8a91-6faeb9bc44ec.png)

**Comment by gina0605** [comment]
올려주신 마지막 이미지에서 contribute 누르시면 PR로 이어지는 걸로 압니다!

**Comment by gina0605** [comment]
올려주신 마지막 이미지에서 contribute 누르시면 PR로 이어지는 걸로 압니다! 그런데 git init을 하는 게 맞나요? 그것 때문에 9 commits behind라고 뜨는 것 같습니다.

**Comment by keetae423** [comment]
> 올려주신 마지막 이미지에서 contribute 누르시면 PR로 이어지는 걸로 압니다! 그런데 git init을 하는 게 맞나요? 그것 때문에 9 commits behind라고 뜨는 것 같습니다.

답변 정말 감사합니다. 덕분에 해결했습니다.
