### ISSUE TITLE
저를 주워가세요

### ISSUE THREAD

**Issue by rickyini3028** [swsnu/swppfall2022#17]
안녕하세요, 이번 학기 같이 하실 팀을 찾습니다.
저는 컴공 주전공이고 졸업이 다가와 시간이 매우 많습니다.
전공 수업들을 들으며 시간을 갈아넣어 보았고, 시간표가 널널해서 이번에도 갈아넣을 수 있을 것이라 생각합니다.
개발을 잘하지는 못하더라도 탈주 없이 "쟤 열심히는 하네" 소리는 듣겠습니다.

rickyini3028@naver.com 으로 연락 부탁드립니다!

**Comment by prodigy-sub** [comment]
혹시 팀원 구하셨나요? 저희 현재 3명인데 관심있으시다면 톡방 초대드리겠습니다!

**Comment by rickyini3028** [comment]
010-9182-7579 입니다

네이버 메일 앱에서 보냈습니다.
날짜: 2022.09.06 오후 01:49:32 (GMT+09:00)
제목: Re: [swsnu/swppfall2022] 저를 주워가세요 (Issue #17)

혹시 팀원 구하셨나요? 저희 현재 3명인데 관심있으시다면 톡방 초대드리겠습니다!
