### ISSUE TITLE
팀원을 모집합니다!

### ISSUE THREAD

**Issue by jaeyoungleeee** [swsnu/swppfall2022#20]
함께 하실 조원을 **두 분 더 모집**합니다.
(현재 작성자 포함 두 명 모집완료)

---
#### 현재 구성원들 소개
   - 다년 간의 현업 백엔드 개발 경험(Django 사용)이 있습니다.

#### 함께 하실 분께 원하는 것 
   - 성실한 자세 (출석, 빠른 카톡 답변)
   - 충분히 시간을 투자할 수 있는 상황

#### 아래 경험이 있으면 선호합니다.
   - 프론트엔드 개발 경험
   - 디자인 경험
   - 다수의 전공 수업 수강 경험

--- 
관심 있으신 분들은 아래와 같이 연락주시면 감사하겠습니다!
- **jerry96@snu.ac.kr**  로
- 본인의 카톡 아이디 혹은 핸드폰 번호
- 간단한 자기 소개(학년, 전공 수업 및 개발 경험, 개발자 진로 희망 여부 등)를 담아서 

감사합니다!

**Comment by keetae423** [comment]
이메일 확인해주시면 감사하겠습니다!

**Comment by jaeyoungleeee** [comment]
@keetae423 메일로 답장 드렸습니다.
