### ISSUE TITLE
한학기동안 함께할 팀원을 구합니다

### ISSUE THREAD

**Issue by DoohyunHwang97** [swsnu/swppfall2022#35]
안녕하세요
저는 개발자를 꿈꾸고 있는 타학과 수강생입니다.
이번 프로젝트를 통해 다른 분들과 협업하고 같이 성장할 수 있는 팀원을 찾고 있습니다. 
제 장점은 의사소통, 열정, 시간입니다. 
물론 기본적인 코딩실력도 중요하지만 저도 그렇고 부족한 부분들은 노력으로 채워나갈 수 있다고 보기에 서로 활발하게 질문하고 도움을 주는 것을 통해 같이 성장해나가는 것을 원하는 분을 찾고 있습니다.

프론트와 백엔드 및 기본적인 CS지식은 갖추고 있고 mysql을 이용해 데이터베이스를 다룬 경험, API,EC2 및 네트워크 통신을 통해서 간단한 서버를 운영한 경험이 있습니다. 또한 창업준비를 했기 때문에 기획 관련 지식도 조금은 있습니다. 

연락주시면 감사하겠습니다 (카톡아이디: hdooh97)

**Comment by jaewooMaeng** [comment]
안녕하세요.
혹시 팀을 구하셨을까요?
구하셨다면 issue를 닫아주시고 못 구하셨다면 [swpp.22.ta@spl.snu.ac.kr](mailto:swpp.22.ta@spl.snu.ac.kr)로 알려주시면 감사하겠습니다 :)
